[package]
name = "completionist-archiver"
version = "0.1.6"
edition = "2021"
license = "MIT"
repository = "https://github.com/hashblen/completionist-archiver"
publish = false
readme = "README.md"
homepage = "https://github.com/hashblen/completionist-archiver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.4", features = ["derive"] }
color-eyre = "0.6.3"
pcap = "2.0.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
ureq = { version = "2.9.7", features = ["json"] }

[dependencies.reliquary]
git = "https://github.com/IceDynamix/reliquary"
tag = "v1.0.1"

[profile.release]
opt-level = "z"  # optimize for size
lto = true